### ISSUE TITLE
System.AggregateException on LokiLogEntryProcessor

### ISSUE THREAD

**Issue by werebear73-tritelph** [hannahchan/LokiLoggingProvider#4]
I'm getting the following error

System.AggregateException: 'An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'LokiLogEntryProcessor'.)'

Inner Exception:
ObjectDisposedException: Cannot access a disposed object.
Object name: 'LokiLogEntryProcessor'.

It is strange that I don't get the error if I don't call my custom Configuration Builder.  This is running on .Net 8.  I tried removing any references to logging in the custom Configuration Builder and the error occurs.  If I remove the configuration builder, I don't get the error but of course I don't get my needed configurations.

**Comment by galensoft** [comment]
Hi, I also got this error!

**Comment by galensoft** [comment]
Caveat: I haven't written an asp.net logger before. I investigated a little bit and it seems that the LokiLogEntryProcesser is disposed at 2 places in LokiLoggerProvider: in the options' OnChange callback and when the provider itself gets disposed. I debugged and it is indeed the OnChange callback that is disposing the loggerFactory which in turn Disposes the processor. The next call to EnqueueMessage then throws the ObjectDisposedException.

In my app, I am downloading objects to a folder next to the binary which might be why the the OnChange callback is called even though no options have actually changed. I suspect this doesn't happen very commonly and while writing this I'm not sure how to fix this but maybe one of the creators know?

**Comment by galensoft** [comment]
Changing the appsettings.json also triggers the error.

**Comment by hannahchan** [comment]
Just a heads up that I'll be archiving this project soon and will be closing all issues. I don't have capacity or motivation to keep maintaining it.

I now recommend using OpenTelemetry in your .NET application to export logs via the OpenTelemetry Protocol (OTLP). OpenTelemetry is a vendor-agnostic framework with strong industry support and both Grafana Loki and Grafana Cloud Logs now support ingesting logs via OTLP.

Both OpenTelemetry and Grafana Loki have matured considerably since this project was conceived.
